apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  labels:
    app: {{ include "gatekeeper.name" . }}
    chart: {{ include "gatekeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  gatekeeper_mapping
      prefix: /
      host: {{ .Values.ingress.host }}
      service: {{ include "gatekeeper.fullname" . }}.default
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "gatekeeper.name" . }}
    release: {{ .Release.Name }}
